version: '3.9'

services:
  db:
    container_name: nest-clean-pg
    image: bitnami/postgresql
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
  